### ISSUE TITLE
Preserve order of issues

### ISSUE THREAD

**Issue by egmanoj** [gotsunami/gitlab-copy#10]
Can the order of issues be preserved?  This will help preserve issue numbers when copying issues from an existing project to a project that doesn't have any.

**Comment by matm** [comment]
Well, they should be ordered. I migrated a project with 300+ issues, all ordered on target. Are those target numbers in reversed order? Random?

**Comment by egmanoj** [comment]
I found the numbers to be random (as far as I can tell). Will try again with a fresh project and revert.

**Comment by egmanoj** [comment]
Order of issues *is* preserved. Closing this.
