### ISSUE TITLE
Labels are not applied to closed issues

### ISSUE THREAD

**Issue by egmanoj** [gotsunami/gitlab-copy#11]
When migrating issues from one project to another labels are not applied to issues that are already closed. Open issues *are* correctly labelled.

**Comment by egmanoj** [comment]
(speculation) Should [this line](https://github.com/gotsunami/gitlab-copy/blob/master/src/command/gitlab-copy/migration.go#L196) supply labels also when calling `UpdateIssue`?

**Comment by matm** [comment]
Merged in f25b187. Thanks @egmanoj!
