### ISSUE TITLE
Linked attachments are not transferred

### ISSUE THREAD

**Issue by nbigaouette** [gotsunami/gitlab-copy#15]
I've run `gitlab-copy` between two GitLab v8.8.3 to transfer issues from one to the other.

Unfortunately, files that were attached to the source issues are not transferred to the new server. When referring to them in an issue (for example, showing a screenshot), the link is broken.

**Comment by matm** [comment]
You are right. Thanks for reporting!

**Comment by matm** [comment]
Just a quick follow up. This feature requires an upstream path to the GitLab Go API currently used. I'm working on it.

**Comment by matm** [comment]
This issue has a high priority now for upcoming 0.7 release. Many users need it.

See https://gitlab.com/gitlab-org/gitlab-ce/issues/21863#note_115268384

**Comment by matm** [comment]
@nbigaouette I just ran a couple of tests adding attachments to issues (both in issue's description body and in comments). It works as expected, all the attachments are copied and available in the duplicated issues.

Could you try on a recent build (like 76eec12)? thanks

**Comment by matm** [comment]
I ran may other tests, all attachments are transferred and downloadable, so I'm pretty confident closing this issue.

**Comment by jeffsheets** [comment]
Does this option need to be enabled in some way? I just copied some issues with image uploads in the description, but the images do not appear in the newly created issues in the other project

**Comment by Zubastic** [comment]
This problem appearing when u try to copy object between different instances of gitlab.
