### ISSUE TITLE
Emails are sent out while mirroring

### ISSUE THREAD

**Issue by nedelenbos** [gotsunami/gitlab-copy#19]
When using the gitlab-copy script, for each new issue emails are sent to the people that are referenced in that issue. Preferably this should be disabled during import time (when possible).

**Comment by matm** [comment]
That may not be that easy to implement: every user defines custom notification policies. So the `gitlab-copy` tool would need to modify user settings, which I find too intrusive (and it would need an administrator token to be able to do that).

Maybe an easier way would be, if possible, to disable temporarily email sending when you migrate issues?

**Comment by nedelenbos** [comment]
I agree upon that being too intrusive, this was just something that I stumbled upon when migrating.. I'm not an expert on the Gitlab API, but if they don't support it (yet), there's little that your tool can do unfortunately indeed..

**Comment by matm** [comment]
Exactly, so I'm closing this issue for now. Thanks for reporting it!
