### ISSUE TITLE
Sign in Error while execute the command

### ISSUE THREAD

**Issue by struchjuliankomma** [gotsunami/gitlab-copy#43]
Hi,

i very happy to found this. I wrote the gitlab.yml and executed the command but i get the following error ` GET https://gitlab.com/soemthing/api/v4/projects/xx/some-project: 401 {error: You need to sign in or sign up before continuing.}`

I am logged in and the token is freshly made with all permissions.

i hope you can help me here.

edit: my adress in the yaml file is `https://gitlab.com/mydomain` and not `https://gitlab.mydomain.com` is that a problem?

Kind Regards 
Julian

**Comment by zahidmb** [comment]
Hi struchjuliankomma,
 did you find any solution of your problem? I am also facing same problem and still unable to sort out it.

**Comment by matm** [comment]
Will reopen if needed.
