### ISSUE TITLE
0 Issues found from Source. (Different Instance)

### ISSUE THREAD

**Issue by PareshSolankiMI** [gotsunami/gitlab-copy#45]
I tried to move all issues in one repo. from my gitlab instance to [Gitlab Main](https://gitlab.com). But I just got message like: 

`source: finding issues ... OK`
`source: 0 issues (0 opened, 0 closed)`
`source: 0 notes`

And if I put source and target same my instance url then it works

I think this issue related to user mapping. I can't understand If I just put target in all users tokens then how will library identify.

**Comment by kayarre** [comment]
I am having this same issue.

**Comment by matm** [comment]
Fixed by #55. Distinct GitLab instances now supported.
