### ISSUE TITLE
no Go files in /root/go/src/github.com/gotsunami/gitlab-copy

### ISSUE THREAD

**Issue by shakisha** [gotsunami/gitlab-copy#47]
I have got a trouble during install, this is the result:

```#go get -u github.com/gotsunami/gitlab-copy```

´´´package github.com/gotsunami/gitlab-copy: no Go files in /root/go/src/github.com/gotsunami/gitlab-copy
´´´

**Comment by matm** [comment]
Thanks for reporting, will have a look ASAP. Meanwhile can you try
```
$ go install github.com/gotsunami/gitlab-copy/cmd/gitlab-copy
```
