### ISSUE TITLE
User ID Mapping

### ISSUE THREAD

**Issue by ragboy** [gotsunami/gitlab-copy#5]
I can understand why you added the "User Name @userid Wrote..." on each comment, that makes sense to not have to workout the actual db ids of the users. However, I wonder if the YML could include some type of user id mapping, so that you don't have as much work to do to workout the mapping in the code.

**Comment by ragboy** [comment]
Realizing you are using the API for this, I guess this would be possible if a gitlab admin (as I am) can get tokens for the users and put in the yml.

**Comment by matm** [comment]
Well, that would be pretty nice indeed. Mapping a list of users with their target GitLab tokens would be useful.
