### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by georgearmenta** [gotsunami/gitlab-copy#54]
Hello @cacciaresi @egmanoj @matm @jflemer-ndp @aboutofpluto 

It looks like last update was 4 years ago.

Is there a plan to update the project or is it completely abandoned?

Thanks

**Comment by matm** [comment]
Hi @georgearmenta, thanks for your interest in this project.

I can say this project is *not dead*. Sometimes it can be hard to find some spare time to work on it.

But thanks for asking, it's good for motivation :) I plan to do some work on #53 soon.

I think a quick review of all pending issues would be of interest. Maybe you can/want to help a bit so we can sort them by priority for example, that would be a good start.

Thank you.

**Comment by georgearmenta** [comment]
Hello @matm, thanks for the quick reply. 

As I don't have experience with Golang, currently I am trying to build the project by myself :) Because I need to run it across a self-signed served Gitlab instance.

I have 2 different Gitlab instances which one of them has self-signed SSL certificate.

I am trying to copy/mirror issues including notes, attachments, labels etc.

I am trying to build the project for accepting self signed certificate but if I cannot manage it, I am going to develop it on Python (as I have some experience on it)

If there is some hope, I can wait for it.

Thank you

**Comment by matm** [comment]
Okay, can you please open an issue about dealing with self-signed SSL instances? I will get back to you about it next week, if you can wait a couple of days.

I first need to fix #55 before using this rather old code base.

**Comment by georgearmenta** [comment]
Hey @cacciaresi @egmanoj @matm @jflemer-ndp @aboutofpluto

Is everything all right?

**Comment by aboutofpluto** [comment]
Hello @georgearmenta,

Depends on what you mean :)
From my side, I haven't written any golang line for ages and won't be of much help, sorry :(

I know that @matm found some time recently to work on this project.
As far as I understand, this issue is closed because it was fixed and merged:  https://github.com/gotsunami/gitlab-copy/commit/e3ae886e6d2ae10ae5d07d8eff668a90ae6ca3d0

Best,
Anthony

**Comment by georgearmenta** [comment]
Hello @aboutofpluto 

Thanks for your kindly response.

Actually @matm was working on updates of the project but at some point, I haven't heard about him. 

The project was stuck on uploading attachments on the issues and for that blocker issue I found another solution;

https://github.com/gotsunami/gitlab-copy/issues/68#issuecomment-1486497605

So I am checking if there is any hope on that.

Thanks

**Comment by matm** [comment]
Hi @georgearmenta 

Sorry for the late answer, I am quite busy these days. I will have a look at the wiki API they offer. Not sure it can work with our use case though but who knows! :)

I will answer in the #68 thread.
