### ISSUE TITLE
Self signed SSL Support

### ISSUE THREAD

**Issue by georgearmenta** [gotsunami/gitlab-copy#57]
Current project doesn't supports Gitlab instances which has self-signed SSL certificates. 

That would be great if you can add support. Thank you.

**Comment by matm** [comment]
Hi @georgearmenta, I have just published a [v0.8.0 version with binaries](https://github.com/gotsunami/gitlab-copy/releases/tag/v0.8.0). It now works with self-signed certs and with different GitLab instances/hosts. Can you give it a try? Thanks!
